# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ffe56162c6ae470f724586bcda34d17cac0d5821b6407ab26cef9c4686a0585b34a286273b60b4efcc766fb5a7e626fe6adce5eea3aed5d1402cc787e49fb0e

test:
  secret_key_base: 569c00994f45558a1f181186f685f76c5ea145f4d6d57693b0e4b9f97423a605734bcfef1f5eec11b9c5e4fd772c5ce6de56e4bb8831a535e6881d44e32094c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
